### PR TITLE
Unselect LOBs when making a distinct select

### LINKED ISSUE #2495: DB2: select distinct with lob/clob fields
## Actual behavior

If a query needs ```distinct``` in a select clause (e.g. join many tables) and a lob/clob field is also in the select, DB2 throws an SQL Exception ```SQLCODE=-134, SQLSTATE=42907,```, cause: https://www.sqlerror.de/db2_sql_error_-134_sqlstate_42907.html 

@rPraml and I implemented a possible solution in our fork: https://github.com/FOCONIS/ebean/pull/55 . 
Our idea is to exclude the lob/clob properties from the ```select distinct``` clauses. These props have to be loaded lazy.
We assume, the same fix would be also good for Oracle,

### Steps to reproduce
Execute the test without the fixes in https://github.com/FOCONIS/ebean/pull/55

@rbygrave can you please check this issue and give us feedback?

### PR DESCRIPTION
**Pull request by rPraml**
Some platforms like DB2, Oracle and also Postgres do not allow to perform a `select distinct` when LOB columns are used.

There was a related issue #900 for postgres, but DB2 does not support `select distinct on (id)`
Workarounds like `cast(lob_column as varchar(32000))` or `DBMS_LOB.substr(lob_column , 32000)` would be not reliable enough. So for these platforms we must not select lobs, when performing a distinct query.

Ebean automatically unselect these columns and rely on lazy load of the properties.

Note: There are some edge cases, when that will not work:
- Ebean unselects the lobs and lazy load is disabled
- the lob is part of a findSingleAttribute-query and distinct is used.
  In this case you can use `select("cast(lobProp as varchar(32000))")` or `fetch("el.path", "cast(lobProp as varchar(32000))")` in your application

This fixes #2495

### CODE REVIEW

File: ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java [hunk 1]
```diff
@@ -1160,7 +1160,26 @@ public boolean isFetchEager() {
...
+    if (lob) {
+      return true;
+    }
+    switch (dbType) {
+    case DbPlatformType.JSON:
+    case DbPlatformType.JSONB:
+      return dbLength == 0; // must be analog to DbPlatformTypeMapping.lookup
+    case DbPlatformType.JSONBlob:
+    case DbPlatformType.JSONClob:
+      return true;
```
Comment (rPraml) [inline ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java:1177]: Should we delegate that decision to the DB-platform?

File: ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilder.java [hunk 2]
```diff
@@ -760,6 +760,10 @@ boolean isPlatformDistinctOn() {
     return dbPlatform.isPlatform(Platform.POSTGRES);
   }
 
+  boolean isPlatformDistinctNoLobs() {
+    return dbPlatform.isPlatform(Platform.DB2); // CHECKME: Also oracle?
```
Comment (rPraml) [inline ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilder.java:764]: I did not yet test that in oracle. That may be also delegated to DatabasePlatform
Maybe returning a enum: 
```java
enum DistinctMode { NORMAL, DISTINCT_ON, UNSELECT_LOBS}
```

File: ebean-test/src/test/java/org/tests/json/TestJsonMapBasic.java [hunk 3]
```diff
@@ -18,15 +23,19 @@
...
-  public void whereManyPredicate() {
+  private final EBasicJsonMap bean = new EBasicJsonMap();;
 
-    if (!isPostgres()) {
-      // testing postgres specific select distinct on clause
-      return;
+  @AfterEach
+  void cleanup() {
+    if (bean != null && bean.getId() != null) {
+      DB.delete(EBasicJsonMap.class, bean.getId());
```
Comment (rPraml) [inline ebean-test/src/test/java/org/tests/json/TestJsonMapBasic.java:31]: refactored cleanup a bit

File: ebean-test/src/test/java/org/tests/json/TestJsonMapBasic.java [hunk 4]
```diff
@@ -50,6 +59,36 @@ public void whereManyPredicate() {
     assertThat(query2.getGeneratedSql()).contains("select distinct on (t0.id) ");
   }
 
+  @Test
+  @ForPlatform(Platform.DB2)
+  public void whereManyPredicateDb2() {
```
Comment (rPraml) [inline ebean-test/src/test/java/org/tests/json/TestJsonMapBasic.java:64]: Unfortunately, the test is not yet starting on current master branch, because of the  `maxTableNameLength` and `maxConstraintNameLength` of 18 char limits in DB2-platform. (changing them to 128 and the test will run)
We will introduce a Legacy/DB2LUW/... platform as suggested  in #2484 soon

File: ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java (hunk 1 above)
Comment (rbygrave) [reply ebean-core/src/main/java/io/ebeaninternal/server/deploy/BeanProperty.java:1177]: At the moment I think the above is good and that we should not delegate this to the DB-platform.  I **_believe_** JSON types are generally more "clob" than "varchar" in nature ... it is a little tempting to not even have the dbLength == 0 check.

**Review by rbygrave — APPROVED** [review]

File: ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilder.java (hunk 2 above)
Comment (rbygrave) [reply ebean-core/src/main/java/io/ebeaninternal/server/query/CQueryBuilder.java:764]: Hmmm, tests all passing with Oracle I believe (last local run, odd problems running oracle test via github workflow)
